# rasa train 
# docker-compose -f docker-compose-local.yml build --no-cache --build-arg RASA_X_VERSION=0.23.3
# docker-compose -f docker-compose-local.yml build --no-cache --build-arg RASA_X_VERSION=0.23.3 --build-arg REPO=https://github.com/rgstephens/rasa-webchat --build-arg BRANCH=links-open-tab
# docker-compose -f docker-compose-local.yml up -d
# docker-compose -f docker-compose-local.yml logs | grep password
# browse to http://localhost:5002 or http://localhost:8080
version: "3.4"

services:
  rasa:
    build:
      context: ./
      dockerfile: Dockerfile.rasax
    ports:
      - "5005:5005"
      - "5002:5002"
    volumes:
      - ./:/app
    #command: rasa x --no-prompt --port 5005 --cors "*" --debug
    command: rasa x --no-prompt --endpoint docker-local/endpoints.yml --port 5005 --cors "*" --debug
  duckling:
    restart: always
    image: "rasa/duckling:latest"
    ports:
      - "8000:8000"
    command: ["duckling-example-exe", "--no-access-log", "--no-error-log"]
  app:
    image: rasa/rasa-sdk:1.5.1
    #build:
    #  context: ./
    #  dockerfile: docker-local/Dockerfile.app
    volumes:
      - ./actions:/app/actions
    ports:
      - "5055:5055"
    command: ["start", "--actions", "actions.actions"]
  mrbot:
    build:
      context: ./
      dockerfile: Dockerfile.mrbot
    ports:
      - "8080:8080"
    command: yarn run webpack-dev-server --config webpack.dev.js --host 0.0.0.0
